first microverse project hello microverse
jossi30/Hello-Microverse pull request #1
Opened 2022-11-28 20:02 UTC by jossi30

2022-11-28 21:31 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle: 

Hi @jossi30, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
 -   No linter errors. :heavy_check_mark: 
 -   Good README file. :heavy_check_mark: 
 -   Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-28 21:31 UTC, Qoosim commented on index.html
> +</body>
- [ ] It is required that a class name should be given to the `h1` and use that class name in your css file to style the content of the `h1` 

![class-name](https://user-images.githubusercontent.com/26597432/204382693-cbdcfd6c-3380-4e76-bc86-de0783f7e6c7.png)

2022-11-28 21:31 UTC, Qoosim commented on style.css
> +}
- [ ] It is best practice to use class name instead element selector. Kindly give a class name to your `h1` tag and use that class name here to style the content of the `h1`.

2022-11-28 21:31 UTC, Qoosim commented on .gitignore
> +test.md
- [ ] I can see that you've added this file to the `.gitignore` but it still reflects on your repository. Follow any of this files to rectify the issue. [This file](https://www.atlassian.com/git/tutorials/saving-changes/gitignore)  or [this file](https://www.pluralsight.com/guides/how-to-use-gitignore-file)

2022-11-29 06:04 UTC, jossi30 commented
added the requirements asked by the reviewer

2022-11-29 06:09 UTC, Olamarx approved these changes
Hi @jossi30, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- All linters passed ✅ 
- Git ignores test.md ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-29 06:12 UTC, merged